Features
Tresor11/News-week pull request #1
Opened 2019-11-08 21:33 UTC by Tresor11

2019-11-08 23:00 UTC, suretrust requested changes
Hi @Tresor11,

### Amazing job thus far. :raised_hands: Just a few suggestions to wrap this up:

- [ ] Please see my comments on your code.

- [x] Let's get rid of the horizontal scroll bar, this insinuates that there is some overflow in your code. Refer to the image below.

![hor](https://user-images.githubusercontent.com/31304943/68514940-87c29580-027f-11ea-8ac4-5aa9cb36b06c.png)

- [x] Some `sections` or `section headers` are missing or named differently on your page, all sections must be present and named as is, on the `Newsweek's website`. This includes the featured stories section, top story section, opinion section, latest news section, more stories section, magazine section, editor's picks section, and featured slideshows section.

- [x] On medium screen, the text is supposed to wrap under the image. Refer to the images below:

**Original**
![wrap](https://user-images.githubusercontent.com/31304943/68515752-3ff13d80-0282-11ea-9cbf-6cbde870f8d5.png)

**Yours**
![wrap2](https://user-images.githubusercontent.com/31304943/68515794-5c8d7580-0282-11ea-9f9f-5f712fb22992.png)

- [x] On medium screen, under the latest news section, the image is more of a thumbnail than full image. Refer to the images below:

**Original**
![img2](https://user-images.githubusercontent.com/31304943/68515958-efc6ab00-0282-11ea-84fa-36060816ecee.png)

**Yours**
![img](https://user-images.githubusercontent.com/31304943/68515963-f81ee600-0282-11ea-8447-bca1f5c36b9e.png)

- [x] On medium screen, around the newsletter area, there are some margin to the left and right. Refer to the images below:

**Original**
![pad](https://user-images.githubusercontent.com/31304943/68516145-85623a80-0283-11ea-8152-65c480ace481.png)

**Yours**
![pad2](https://user-images.githubusercontent.com/31304943/68516155-8c894880-0283-11ea-886f-5c9d6deae37c.png)

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_:tada:

2019-11-08 23:00 UTC, suretrust commented on index.html
> +        </div>
These should be links, not just `div`.

2019-11-08 23:00 UTC, suretrust commented on index.html
> +      <div class="container-fluid ">
This class should be `container`. Kindly take a look at the `newsweek.com` website, you'd notice some margin left and right.

2019-11-09 12:31 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2019-11-09 13:46 UTC, Anna-Myzukina commented
### Hi @konyan! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Wow, your project looks :+1: 
#### But need some Required Changes

Main content
* [x] It contains `Featured stories` section.
* [ ] It contains `Top story` section.
* [x] It contains `Opinion` section.
* [x] It contains `Latest news` section.
* [ ] It contains `More stories` section.
* [ ] It contains `In the magazine` section.
* [ ] It contains `Editor's picks` section.
* [ ] It contains `Featured slideshows` section.
* [ ] **It changes with RWD breakpoints.**

Please check responsiveness:

*** Here space in the right side, but should be full width***
![nw1](https://user-images.githubusercontent.com/26605804/68529370-9a33e200-0306-11ea-8672-8e10a45f39b6.png)

*** Also here button 'Sign in' ***
![nw2](https://user-images.githubusercontent.com/26605804/68529439-7a50ee00-0307-11ea-8ec6-a556e66e79ab.png)

![nw4](https://user-images.githubusercontent.com/26605804/68529451-a1a7bb00-0307-11ea-9a1f-4627c90daa44.png)

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

2019-11-09 14:03 UTC, Anna-Myzukina commented on index.html
> +              <img src="./images/bill-taylor-transcript-released.jpg" class="img-fluid w-100" alt="">
In line 125 should be "TOP STORY"
<h6 class="font-weight-bolder text-muted">TOP STORY</h6>

2019-11-09 14:05 UTC, Anna-Myzukina commented on index.html
> +
Here should be "More stories"

2019-11-09 14:07 UTC, Anna-Myzukina commented on index.html
> +              <h6 class="font-weight-bolder text-muted">LATEST NEWS</h6>
Line 378 Here should be "In the magazine"

2019-11-09 14:08 UTC, Anna-Myzukina commented on index.html
> +              <h6 class="font-weight-bolder d-inline">LATEST NEWS</h6>
Line 484 should be "Editor's picks"

2019-11-09 15:44 UTC, Anna-Myzukina commented
## Project Approved ![image](https://user-images.githubusercontent.com/26605804/68531124-b429f080-0317-11ea-8cc2-690ec0ab647a.png)

### You can merge it and don't forget to fill the project completion form.

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it here. I hope in the next project you can do this!


*Happy coding 😄*

2019-11-09 15:45 UTC, Anna-Myzukina approved these changes

2019-11-09 15:50 UTC, merged